if(${DUNE_CPU_NAME} STREQUAL "x86")
    set(BONMIN_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/vendor/libraries/bonmin_x86/include)
    set(BONMIN_LIBRARY_DIR ${CMAKE_CURRENT_SOURCE_DIR}/vendor/libraries/bonmin_x86/lib)
    include_directories(${BONMIN_INCLUDE_DIR})
    file(GLOB BONMIN_LIBRARIES ${BONMIN_LIBRARY_DIR}/*.a)
    list(APPEND DUNE_VENDOR_LIBRARIES ${BONMIN_LIBRARIES})
else()
    set(BONMIN_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/vendor/libraries/bonmin/include)
    set(BONMIN_LIBRARY_DIR ${CMAKE_CURRENT_SOURCE_DIR}/vendor/libraries/bonmin/lib)
    include_directories(${BONMIN_INCLUDE_DIR})
    file(GLOB BONMIN_LIBRARIES ${BONMIN_LIBRARY_DIR}/*.a)
    list(APPEND DUNE_VENDOR_LIBRARIES ${BONMIN_LIBRARIES})
endif()
